spring:
  profiles:

    active: prod

---
spring:
  config:
    activate:
      on-profile:
        - prod
  cloud:
    config:
      import-check:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/currentAccount?ssl=true&retryWrites=true&w=majority

microservices-urls:
  api-client: ${API_CLIENT_CONFIG}
  api-credit: ${API_CREDIT_CONFIG}
  api-creditcard: ${API_CREDITCARD_CONFIG}

---

spring:
  application:
    name: currentaccount-microservice
  config:
    activate:
      on-profile:
        - dev
    import: optional:configserver:http://localhost:8888

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher